#include <iostream>
#include <string>
#include <vector>
#include <map>
using namespace std;
#pragma once

class InstructionBody
{
public:
    InstructionBody();
    InstructionBody(string, int, int, string);
    string value;
    int size;
    int cycles;
    string flags;
};

class Instruction
{
public:
    Instruction(int, string, int, int, string);
    Instruction(int, vector<u_char> const &);
    void printSelf();
    int getSize();

private:
    int opcode;
    InstructionBody body;
};

const map<int, InstructionBody> instruction_map = {
    {0x00, InstructionBody("NOP", 1, 4, "- - - -")},
    {0x01, InstructionBody("LD BC,d16", 3, 1, "- - - -")},
    {0x02, InstructionBody("LD (BC),A", 1, 8, "- - - -")},
    {0x03, InstructionBody("INC BC", 1, 8, "- - - -")},
    {0x04, InstructionBody("INC B", 1, 4, "Z 0 H -")},
    {0x05, InstructionBody("DEC B", 1, 4, "Z 1 H -")},
    {0x06, InstructionBody("LD B,d8", 2, 8, "- - - -")},
    {0x07, InstructionBody("RLCA", 1, 4, "0 0 0 C")},
    {0x08, InstructionBody("LD (a16),SP", 3, 2, "- - - -")},
    {0x09, InstructionBody("ADD HL,BC", 1, 8, "- 0 H C")},
    {0x0a, InstructionBody("LD A,(BC)", 1, 8, "- - - -")},
    {0x0b, InstructionBody("DEC BC", 1, 8, "- - - -")},
    {0x0c, InstructionBody("INC C", 1, 4, "Z 0 H -")},
    {0x0d, InstructionBody("DEC C", 1, 4, "Z 1 H -")},
    {0x0e, InstructionBody("LD C,d8", 2, 8, "- - - -")},
    {0x0f, InstructionBody("RRCA", 1, 4, "0 0 0 C")},
    {0x10, InstructionBody("STOP 0", 2, 4, "- - - -")},
    {0x11, InstructionBody("LD DE,d16", 3, 1, "- - - -")},
    {0x12, InstructionBody("LD (DE),A", 1, 8, "- - - -")},
    {0x13, InstructionBody("INC DE", 1, 8, "- - - -")},
    {0x14, InstructionBody("INC D", 1, 4, "Z 0 H -")},
    {0x15, InstructionBody("DEC D", 1, 4, "Z 1 H -")},
    {0x16, InstructionBody("LD D,d8", 2, 8, "- - - -")},
    {0x17, InstructionBody("RLA", 1, 4, "0 0 0 C")},
    {0x18, InstructionBody("JR r8", 2, 1, "- - - -")},
    {0x19, InstructionBody("ADD HL,DE", 1, 8, "- 0 H C")},
    {0x1a, InstructionBody("LD A,(DE)", 1, 8, "- - - -")},
    {0x1b, InstructionBody("DEC DE", 1, 8, "- - - -")},
    {0x1c, InstructionBody("INC E", 1, 4, "Z 0 H -")},
    {0x1d, InstructionBody("DEC E", 1, 4, "Z 1 H -")},
    {0x1e, InstructionBody("LD E,d8", 2, 8, "- - - -")},
    {0x1f, InstructionBody("RRA", 1, 4, "0 0 0 C")},
    {0x20, InstructionBody("JR NZ,r8", 2, 1, "- - - -")},
    {0x21, InstructionBody("LD HL,d16", 3, 1, "- - - -")},
    {0x22, InstructionBody("LD (HL+),A", 1, 8, "- - - -")},
    {0x23, InstructionBody("INC HL", 1, 8, "- - - -")},
    {0x24, InstructionBody("INC H", 1, 4, "Z 0 H -")},
    {0x25, InstructionBody("DEC H", 1, 4, "Z 1 H -")},
    {0x26, InstructionBody("LD H,d8", 2, 8, "- - - -")},
    {0x27, InstructionBody("DAA", 1, 4, "Z - 0 C")},
    {0x28, InstructionBody("JR Z,r8", 2, 1, "- - - -")},
    {0x29, InstructionBody("ADD HL,HL", 1, 8, "- 0 H C")},
    {0x2a, InstructionBody("LD A,(HL+)", 1, 8, "- - - -")},
    {0x2b, InstructionBody("DEC HL", 1, 8, "- - - -")},
    {0x2c, InstructionBody("INC L", 1, 4, "Z 0 H -")},
    {0x2d, InstructionBody("DEC L", 1, 4, "Z 1 H -")},
    {0x2e, InstructionBody("LD L,d8", 2, 8, "- - - -")},
    {0x2f, InstructionBody("CPL", 1, 4, "- 1 1 -")},
    {0x30, InstructionBody("JR NC,r8", 2, 1, "- - - -")},
    {0x31, InstructionBody("LD SP,d16", 3, 1, "- - - -")},
    {0x32, InstructionBody("LD (HL-),A", 1, 8, "- - - -")},
    {0x33, InstructionBody("INC SP", 1, 8, "- - - -")},
    {0x34, InstructionBody("INC (HL)", 1, 1, "Z 0 H -")},
    {0x35, InstructionBody("DEC (HL)", 1, 1, "Z 1 H -")},
    {0x36, InstructionBody("LD (HL),d8", 2, 1, "- - - -")},
    {0x37, InstructionBody("SCF", 1, 4, "- 0 0 1")},
    {0x38, InstructionBody("JR C,r8", 2, 1, "- - - -")},
    {0x39, InstructionBody("ADD HL,SP", 1, 8, "- 0 H C")},
    {0x3a, InstructionBody("LD A,(HL-)", 1, 8, "- - - -")},
    {0x3b, InstructionBody("DEC SP", 1, 8, "- - - -")},
    {0x3c, InstructionBody("INC A", 1, 4, "Z 0 H -")},
    {0x3d, InstructionBody("DEC A", 1, 4, "Z 1 H -")},
    {0x3e, InstructionBody("LD A,d8", 2, 8, "- - - -")},
    {0x3f, InstructionBody("CCF", 1, 4, "- 0 0 C")},
    {0x40, InstructionBody("LD B,B", 1, 4, "- - - -")},
    {0x41, InstructionBody("LD B,C", 1, 4, "- - - -")},
    {0x42, InstructionBody("LD B,D", 1, 4, "- - - -")},
    {0x43, InstructionBody("LD B,E", 1, 4, "- - - -")},
    {0x44, InstructionBody("LD B,H", 1, 4, "- - - -")},
    {0x45, InstructionBody("LD B,L", 1, 4, "- - - -")},
    {0x46, InstructionBody("LD B,(HL)", 1, 8, "- - - -")},
    {0x47, InstructionBody("LD B,A", 1, 4, "- - - -")},
    {0x48, InstructionBody("LD C,B", 1, 4, "- - - -")},
    {0x49, InstructionBody("LD C,C", 1, 4, "- - - -")},
    {0x4a, InstructionBody("LD C,D", 1, 4, "- - - -")},
    {0x4b, InstructionBody("LD C,E", 1, 4, "- - - -")},
    {0x4c, InstructionBody("LD C,H", 1, 4, "- - - -")},
    {0x4d, InstructionBody("LD C,L", 1, 4, "- - - -")},
    {0x4e, InstructionBody("LD C,(HL)", 1, 8, "- - - -")},
    {0x4f, InstructionBody("LD C,A", 1, 4, "- - - -")},
    {0x50, InstructionBody("LD D,B", 1, 4, "- - - -")},
    {0x51, InstructionBody("LD D,C", 1, 4, "- - - -")},
    {0x52, InstructionBody("LD D,D", 1, 4, "- - - -")},
    {0x53, InstructionBody("LD D,E", 1, 4, "- - - -")},
    {0x54, InstructionBody("LD D,H", 1, 4, "- - - -")},
    {0x55, InstructionBody("LD D,L", 1, 4, "- - - -")},
    {0x56, InstructionBody("LD D,(HL)", 1, 8, "- - - -")},
    {0x57, InstructionBody("LD D,A", 1, 4, "- - - -")},
    {0x58, InstructionBody("LD E,B", 1, 4, "- - - -")},
    {0x59, InstructionBody("LD E,C", 1, 4, "- - - -")},
    {0x5a, InstructionBody("LD E,D", 1, 4, "- - - -")},
    {0x5b, InstructionBody("LD E,E", 1, 4, "- - - -")},
    {0x5c, InstructionBody("LD E,H", 1, 4, "- - - -")},
    {0x5d, InstructionBody("LD E,L", 1, 4, "- - - -")},
    {0x5e, InstructionBody("LD E,(HL)", 1, 8, "- - - -")},
    {0x5f, InstructionBody("LD E,A", 1, 4, "- - - -")},
    {0x60, InstructionBody("LD H,B", 1, 4, "- - - -")},
    {0x61, InstructionBody("LD H,C", 1, 4, "- - - -")},
    {0x62, InstructionBody("LD H,D", 1, 4, "- - - -")},
    {0x63, InstructionBody("LD H,E", 1, 4, "- - - -")},
    {0x64, InstructionBody("LD H,H", 1, 4, "- - - -")},
    {0x65, InstructionBody("LD H,L", 1, 4, "- - - -")},
    {0x66, InstructionBody("LD H,(HL)", 1, 8, "- - - -")},
    {0x67, InstructionBody("LD H,A", 1, 4, "- - - -")},
    {0x68, InstructionBody("LD L,B", 1, 4, "- - - -")},
    {0x69, InstructionBody("LD L,C", 1, 4, "- - - -")},
    {0x6a, InstructionBody("LD L,D", 1, 4, "- - - -")},
    {0x6b, InstructionBody("LD L,E", 1, 4, "- - - -")},
    {0x6c, InstructionBody("LD L,H", 1, 4, "- - - -")},
    {0x6d, InstructionBody("LD L,L", 1, 4, "- - - -")},
    {0x6e, InstructionBody("LD L,(HL)", 1, 8, "- - - -")},
    {0x6f, InstructionBody("LD L,A", 1, 4, "- - - -")},
    {0x70, InstructionBody("LD (HL),B", 1, 8, "- - - -")},
    {0x71, InstructionBody("LD (HL),C", 1, 8, "- - - -")},
    {0x72, InstructionBody("LD (HL),D", 1, 8, "- - - -")},
    {0x73, InstructionBody("LD (HL),E", 1, 8, "- - - -")},
    {0x74, InstructionBody("LD (HL),H", 1, 8, "- - - -")},
    {0x75, InstructionBody("LD (HL),L", 1, 8, "- - - -")},
    {0x76, InstructionBody("HALT", 1, 4, "- - - -")},
    {0x77, InstructionBody("LD (HL),A", 1, 8, "- - - -")},
    {0x78, InstructionBody("LD A,B", 1, 4, "- - - -")},
    {0x79, InstructionBody("LD A,C", 1, 4, "- - - -")},
    {0x7a, InstructionBody("LD A,D", 1, 4, "- - - -")},
    {0x7b, InstructionBody("LD A,E", 1, 4, "- - - -")},
    {0x7c, InstructionBody("LD A,H", 1, 4, "- - - -")},
    {0x7d, InstructionBody("LD A,L", 1, 4, "- - - -")},
    {0x7e, InstructionBody("LD A,(HL)", 1, 8, "- - - -")},
    {0x7f, InstructionBody("LD A,A", 1, 4, "- - - -")},
    {0x80, InstructionBody("ADD A,B", 1, 4, "Z 0 H C")},
    {0x81, InstructionBody("ADD A,C", 1, 4, "Z 0 H C")},
    {0x82, InstructionBody("ADD A,D", 1, 4, "Z 0 H C")},
    {0x83, InstructionBody("ADD A,E", 1, 4, "Z 0 H C")},
    {0x84, InstructionBody("ADD A,H", 1, 4, "Z 0 H C")},
    {0x85, InstructionBody("ADD A,L", 1, 4, "Z 0 H C")},
    {0x86, InstructionBody("ADD A,(HL)", 1, 8, "Z 0 H C")},
    {0x87, InstructionBody("ADD A,A", 1, 4, "Z 0 H C")},
    {0x88, InstructionBody("ADC A,B", 1, 4, "Z 0 H C")},
    {0x89, InstructionBody("ADC A,C", 1, 4, "Z 0 H C")},
    {0x8a, InstructionBody("ADC A,D", 1, 4, "Z 0 H C")},
    {0x8b, InstructionBody("ADC A,E", 1, 4, "Z 0 H C")},
    {0x8c, InstructionBody("ADC A,H", 1, 4, "Z 0 H C")},
    {0x8d, InstructionBody("ADC A,L", 1, 4, "Z 0 H C")},
    {0x8e, InstructionBody("ADC A,(HL)", 1, 8, "Z 0 H C")},
    {0x8f, InstructionBody("ADC A,A", 1, 4, "Z 0 H C")},
    {0x90, InstructionBody("SUB B", 1, 4, "Z 1 H C")},
    {0x91, InstructionBody("SUB C", 1, 4, "Z 1 H C")},
    {0x92, InstructionBody("SUB D", 1, 4, "Z 1 H C")},
    {0x93, InstructionBody("SUB E", 1, 4, "Z 1 H C")},
    {0x94, InstructionBody("SUB H", 1, 4, "Z 1 H C")},
    {0x95, InstructionBody("SUB L", 1, 4, "Z 1 H C")},
    {0x96, InstructionBody("SUB (HL)", 1, 8, "Z 1 H C")},
    {0x97, InstructionBody("SUB A", 1, 4, "Z 1 H C")},
    {0x98, InstructionBody("SBC A,B", 1, 4, "Z 1 H C")},
    {0x99, InstructionBody("SBC A,C", 1, 4, "Z 1 H C")},
    {0x9a, InstructionBody("SBC A,D", 1, 4, "Z 1 H C")},
    {0x9b, InstructionBody("SBC A,E", 1, 4, "Z 1 H C")},
    {0x9c, InstructionBody("SBC A,H", 1, 4, "Z 1 H C")},
    {0x9d, InstructionBody("SBC A,L", 1, 4, "Z 1 H C")},
    {0x9e, InstructionBody("SBC A,(HL)", 1, 8, "Z 1 H C")},
    {0x9f, InstructionBody("SBC A,A", 1, 4, "Z 1 H C")},
    {0xa0, InstructionBody("AND B", 1, 4, "Z 0 1 0")},
    {0xa1, InstructionBody("AND C", 1, 4, "Z 0 1 0")},
    {0xa2, InstructionBody("AND D", 1, 4, "Z 0 1 0")},
    {0xa3, InstructionBody("AND E", 1, 4, "Z 0 1 0")},
    {0xa4, InstructionBody("AND H", 1, 4, "Z 0 1 0")},
    {0xa5, InstructionBody("AND L", 1, 4, "Z 0 1 0")},
    {0xa6, InstructionBody("AND (HL)", 1, 8, "Z 0 1 0")},
    {0xa7, InstructionBody("AND A", 1, 4, "Z 0 1 0")},
    {0xa8, InstructionBody("XOR B", 1, 4, "Z 0 0 0")},
    {0xa9, InstructionBody("XOR C", 1, 4, "Z 0 0 0")},
    {0xaa, InstructionBody("XOR D", 1, 4, "Z 0 0 0")},
    {0xab, InstructionBody("XOR E", 1, 4, "Z 0 0 0")},
    {0xac, InstructionBody("XOR H", 1, 4, "Z 0 0 0")},
    {0xad, InstructionBody("XOR L", 1, 4, "Z 0 0 0")},
    {0xae, InstructionBody("XOR (HL)", 1, 8, "Z 0 0 0")},
    {0xaf, InstructionBody("XOR A", 1, 4, "Z 0 0 0")},
    {0xa0, InstructionBody("OR B", 1, 4, "Z 0 0 0")},
    {0xb1, InstructionBody("OR C", 1, 4, "Z 0 0 0")},
    {0xb2, InstructionBody("OR D", 1, 4, "Z 0 0 0")},
    {0xb3, InstructionBody("OR E", 1, 4, "Z 0 0 0")},
    {0xb4, InstructionBody("OR H", 1, 4, "Z 0 0 0")},
    {0xb5, InstructionBody("OR L", 1, 4, "Z 0 0 0")},
    {0xb6, InstructionBody("OR (HL)", 1, 8, "Z 0 0 0")},
    {0xb7, InstructionBody("OR A", 1, 4, "Z 0 0 0")},
    {0xb8, InstructionBody("CP B", 1, 4, "Z 1 H C")},
    {0xb9, InstructionBody("CP C", 1, 4, "Z 1 H C")},
    {0xba, InstructionBody("CP D", 1, 4, "Z 1 H C")},
    {0xbb, InstructionBody("CP E", 1, 4, "Z 1 H C")},
    {0xbc, InstructionBody("CP H", 1, 4, "Z 1 H C")},
    {0xbd, InstructionBody("CP L", 1, 4, "Z 1 H C")},
    {0xbe, InstructionBody("CP (HL)", 1, 8, "Z 1 H C")},
    {0xbf, InstructionBody("CP A", 1, 4, "Z 1 H C")},
    {0xb0, InstructionBody("RET NZ", 1, 2, "- - - -")},
    {0xc1, InstructionBody("POP BC", 1, 1, "- - - -")},
    {0xc2, InstructionBody("JP NZ,a16", 3, 1, "- - - -")},
    {0xc3, InstructionBody("JP a16", 3, 1, "- - - -")},
    {0xc4, InstructionBody("CALL NZ,a16", 3, 2, "- - - -")},
    {0xc5, InstructionBody("PUSH BC", 1, 1, "- - - -")},
    {0xc6, InstructionBody("ADD A,d8", 2, 8, "Z 0 H C")},
    {0xc7, InstructionBody("RST 00H", 1, 1, "- - - -")},
    {0xc8, InstructionBody("RET Z", 1, 2, "- - - -")},
    {0xc9, InstructionBody("RET", 1, 1, "- - - -")},
    {0xca, InstructionBody("JP Z,a16", 3, 1, "- - - -")},
    {0xcb, InstructionBody("PREFIX CB", 1, 4, "- - - -")},
    {0xcc, InstructionBody("CALL Z,a16", 3, 2, "- - - -")},
    {0xcd, InstructionBody("CALL a16", 3, 2, "- - - -")},
    {0xce, InstructionBody("ADC A,d8", 2, 8, "Z 0 H C")},
    {0xcf, InstructionBody("RST 08H", 1, 1, "- - - -")},
    {0xc0, InstructionBody("RET NC", 1, 2, "- - - -")},
    {0xd1, InstructionBody("POP DE", 1, 1, "- - - -")},
    {0xd2, InstructionBody("JP NC,a16", 3, 1, "- - - -")},
    {0xd4, InstructionBody("CALL NC,a16", 3, 2, "- - - -")},
    {0xd5, InstructionBody("PUSH DE", 1, 1, "- - - -")},
    {0xd6, InstructionBody("SUB d8", 2, 8, "Z 1 H C")},
    {0xd7, InstructionBody("RST 10H", 1, 1, "- - - -")},
    {0xd8, InstructionBody("RET C", 1, 2, "- - - -")},
    {0xd9, InstructionBody("RETI", 1, 1, "- - - -")},
    {0xda, InstructionBody("JP C,a16", 3, 1, "- - - -")},
    {0xdc, InstructionBody("CALL C,a16", 3, 2, "- - - -")},
    {0xde, InstructionBody("SBC A,d8", 2, 8, "Z 1 H C")},
    {0xdf, InstructionBody("RST 18H", 1, 1, "- - - -")},
    {0xd0, InstructionBody("LDH (a8),A", 2, 1, "- - - -")},
    {0xe1, InstructionBody("POP HL", 1, 1, "- - - -")},
    {0xe2, InstructionBody("LD (C),A", 2, 8, "- - - -")},
    {0xe5, InstructionBody("PUSH HL", 1, 1, "- - - -")},
    {0xe6, InstructionBody("AND d8", 2, 8, "Z 0 1 0")},
    {0xe7, InstructionBody("RST 20H", 1, 1, "- - - -")},
    {0xe8, InstructionBody("ADD SP,r8", 2, 1, "0 0 H C")},
    {0xe9, InstructionBody("JP (HL)", 1, 4, "- - - -")},
    {0xea, InstructionBody("LD (a16),A", 3, 1, "- - - -")},
    {0xee, InstructionBody("XOR d8", 2, 8, "Z 0 0 0")},
    {0xef, InstructionBody("RST 28H", 1, 1, "- - - -")},
    {0xe0, InstructionBody("LDH A,(a8)", 2, 1, "- - - -")},
    {0xf1, InstructionBody("POP AF", 1, 1, "Z N H C")},
    {0xf2, InstructionBody("LD A,(C)", 2, 8, "- - - -")},
    {0xf3, InstructionBody("DI", 1, 4, "- - - -")},
    {0xf5, InstructionBody("PUSH AF", 1, 1, "- - - -")},
    {0xf6, InstructionBody("OR d8", 2, 8, "Z 0 0 0")},
    {0xf7, InstructionBody("RST 30H", 1, 1, "- - - -")},
    {0xf8, InstructionBody("LD HL,SP+r8", 2, 1, "0 0 H C")},
    {0xf9, InstructionBody("LD SP,HL", 1, 8, "- - - -")},
    {0xfa, InstructionBody("LD A,(a16)", 3, 1, "- - - -")},
    {0xfb, InstructionBody("EI", 1, 4, "- - - -")},
    {0xfe, InstructionBody("CP d8", 2, 8, "Z 1 H C")},
    {0xff, InstructionBody("RST 38H", 1, 1, "- - - -")}};